version: '3.8'

services:
  django:
    build:
      context: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - media:/app/media
      - ./static:/app/static
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django

volumes:
  media:
